### ISSUE TITLE
# Training Error Report

### ISSUE THREAD

**Issue by dustasa** [LukeJaffe/GFN#1]
Hi there, I have tried train GFN in my own device(3090ti-24G) by using 
`osr_run --trial_config=./configs/prw_train_final.yaml`
set batch size to 4  and change debug to True, 
while I got failed as below, have you ever meet the same problem? Hoping for your reply.
```python
==> Computing detections and embeddings
100% 6112/6112 [11:01<00:00,  9.24it/s]
==> Computing detection performance
100%|██████████| 6112/6112 [00:09<00:00, 654.58it/s]
num_det_tot: 27972
gt/tot: 23809 25062
100%|██████████| 6112/6112 [00:07<00:00, 798.01it/s]
num_det_tot: 25062
gt/tot: 25062 25062
det:
{'test_ap@0.5': 0.9250273006517983, 'test_recall@0.5': 0.9500039901045407}
gt:
{'test_ap@0.5': 1.0, 'test_recall@0.5': 1.0}
==> Computing retrieval performance (protocol)
==> Protocol: test
  0%|          | 0/2057 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/.local/bin/osr_run", line 33, in <module>
    sys.exit(load_entry_point('osr-lib==1.0.0', 'console_scripts', 'osr_run')())
  File "/home/.local/lib/python3.7/site-packages/osr_lib-1.0.0-py3.7.egg/osr/engine/main.py", line 439, in main
  File "/home/.local/lib/python3.7/site-packages/osr_lib-1.0.0-py3.7.egg/osr/engine/main.py", line 333, in run
  File "/home/anaconda3/envs/osr/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/.local/lib/python3.7/site-packages/osr_lib-1.0.0-py3.7.egg/osr/engine/evaluate.py", line 201, in evaluate_performance
  File "/home/.local/lib/python3.7/site-packages/osr_lib-1.0.0-py3.7.egg/osr/engine/evaluate.py", line 505, in evaluate_retrieval_orig
  File "/home/anaconda3/envs/osr/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 233, in average_precision_score
    average_precision, y_true, y_score, average, sample_weight=sample_weight
  File "/home/anaconda3/envs/osr/lib/python3.7/site-packages/sklearn/metrics/_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "/home/anaconda3/envs/osr/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 206, in _binary_uninterpolated_average_precision
    y_true, y_score, pos_label=pos_label, sample_weight=sample_weight
  File "/home/anaconda3/envs/osr/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 859, in precision_recall_curve
    y_true, probas_pred, pos_label=pos_label, sample_weight=sample_weight
  File "/home/anaconda3/envs/osr/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 737, in _binary_clf_curve
    assert_all_finite(y_score)
  File "/home/anaconda3/envs/osr/lib/python3.7/site-packages/sklearn/utils/validation.py", line 134, in assert_all_finite
    _assert_all_finite(X.data if sp.issparse(X) else X, allow_nan)
  File "/home/anaconda3/envs/osr/lib/python3.7/site-packages/sklearn/utils/validation.py", line 116, in _assert_all_finite
    type_err, msg_dtype if msg_dtype is not None else X.dtype
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

**Comment by LukeJaffe** [comment]
Thanks for reporting this. Looks like the inputs to average_precision_score contain some bad values (nan or inf). I committed a patch to call np.nan_to_num on the score inputs to each call of average_precision_score. If that doesn't fix it, then there are bad values in the labels, which would require further investigating (don't think that's the case). Let me know if the patch doesn't fix this issue.

**Comment by dustasa** [comment]
Thanks a lot. I have compared diff and apply this patch to the newest code,  
it works fine by using `epochs: 3, eval_interval: 3` in the config yaml. 
I will set `epochs` and `eval_interval` to 30 and see whether it works fine or not , it may take some time. 
Sorry for my late reply, since I lived in China and we use GMT+8.  
The following are the print logs.
```python
==> Computing detections and embeddings
100% 6112/6112 [09:12<00:00, 11.06it/s]
==> Computing detection performance
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6112/6112 [00:04<00:00, 1487.79it/s]
num_det_tot: 29621
gt/tot: 23336 25062
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6112/6112 [00:03<00:00, 1729.33it/s]
num_det_tot: 25062
gt/tot: 25062 25062
det:
{'test_ap@0.5': 0.8960054867690496, 'test_recall@0.5': 0.9311307956268454}
gt:
{'test_ap@0.5': 1.0, 'test_recall@0.5': 1.0}
==> Computing retrieval performance (protocol)
==> Protocol: test
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2057/2057 [06:04<00:00,  5.65it/s]
match: 2057/2057
recall: 74324/77122
num no gt: 0
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2057/2057 [05:57<00:00,  5.76it/s]
match: 2057/2057
recall: 77122/77122
num no gt: 0
det:
{'test_test_det_mAP': 0.00117947768623686,
 'test_test_det_match': 1.0,
 'test_test_det_recall': 0.963719820544073,
 'test_test_det_top1': 0.0}
gt:
{'test_test_gt_mAP': 0.0014963307777562346,
 'test_test_gt_match': 1.0,
 'test_test_gt_recall': 1.0,
 'test_test_gt_top1': 0.0}
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2057/2057 [13:00<00:00,  2.63it/s]
match: 2057/2057
recall: 74324/77122
num no gt: 0
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2057/2057 [13:09<00:00,  2.60it/s]
match: 2057/2057
recall: 77122/77122
num no gt: 0
det:
{'test_test_det_gfn_mAP': 0.00117947768623686,
 'test_test_det_gfn_match': 1.0,
 'test_test_det_gfn_recall': 0.963719820544073,
 'test_test_det_gfn_top1': 0.0,
 'test_test_image_gfn_frac_filter': 0.0,
 'test_test_image_gfn_mAP': 0.006135242146047593,
 'test_test_image_gfn_thresh_filter': nan,
 'test_test_image_gfn_top1': 0.0}
gt:
{'test_test_gt_gfn_mAP': 0.0014963307777562346,
 'test_test_gt_gfn_match': 1.0,
 'test_test_gt_gfn_recall': 1.0,
 'test_test_gt_gfn_top1': 0.0,
 'test_test_image_gfn_frac_filter': 0.0,
 'test_test_image_gfn_mAP': 0.006135242146047593,
 'test_test_image_gfn_thresh_filter': nan,
 'test_test_image_gfn_top1': 0.0}

==> Full metrics:
Saving debug checkpoint epoch 2 to: debug_ckpt/prw_debug_checkpoint_e2.pkl

```

**Comment by LukeJaffe** [comment]
Ok great, glad it's working now. I'd be interested to see your results after 30 epochs, and the total runtime on the 3090.

**Comment by dustasa** [comment]
I have tried 30 epochs in 3090ti-24G, and there are some many `0` or `nan` in the result, could u figure out why does this happened? The full log is attached.
```python
match: 2057/2057
recall: 77122/77122
num no gt: 0
det:
{'test_test_det_gfn_mAP': 0.0012547512162295825,
 'test_test_det_gfn_match': 1.0,
 'test_test_det_gfn_recall': 0.9769585850989342,
 'test_test_det_gfn_top1': 0.0,
 'test_test_image_gfn_frac_filter': 0.0,
 'test_test_image_gfn_mAP': 0.006135242146047593,
 'test_test_image_gfn_thresh_filter': nan,
 'test_test_image_gfn_top1': 0.0}
gt:
{'test_test_gt_gfn_mAP': 0.0014963307777562346,
 'test_test_gt_gfn_match': 1.0,
 'test_test_gt_gfn_recall': 1.0,
 'test_test_gt_gfn_top1': 0.0,
 'test_test_image_gfn_frac_filter': 0.0,
 'test_test_image_gfn_mAP': 0.006135242146047593,
 'test_test_image_gfn_thresh_filter': nan,
 'test_test_image_gfn_top1': 0.0}

==> Full metrics:
Saving debug checkpoint epoch 29 to: debug_ckpt/prw_debug_checkpoint_e29.pkl
{'epoch': 29,
 'gfn_loss': 1.2231624126434326,
 'loss': 1.8785041570663452,
 'loss_box_cls': 0.032540708780288696,
 'loss_box_reg': 0.05091039463877678,
 'loss_proposal_cls': 0.04492741823196411,
 'loss_proposal_reg': 0.3814258873462677,
 'loss_rpn_cls': 0.0025163881946355104,
 'loss_rpn_reg': 0.003297738265246153,
 'lr': 9.999999974752427e-07,
 'sim_loss': 0.13972322642803192,
 'test_ap@0.5': 0.9291702464665603,
 'test_recall@0.5': 0.9553108291437236,
 'test_test_det_gfn_mAP': 0.0012547512162295825,
 'test_test_det_gfn_match': 1.0,
 'test_test_det_gfn_recall': 0.9769585850989342,
 'test_test_det_gfn_top1': 0.0,
 'test_test_det_mAP': 0.0012547512162295825,
 'test_test_det_match': 1.0,
 'test_test_det_recall': 0.9769585850989342,
 'test_test_det_top1': 0.0,
 'test_test_gt_gfn_mAP': 0.0014963307777562346,
 'test_test_gt_gfn_match': 1.0,
 'test_test_gt_gfn_recall': 1.0,
 'test_test_gt_gfn_top1': 0.0,
 'test_test_gt_mAP': 0.0014963307777562346,
 'test_test_gt_match': 1.0,
 'test_test_gt_recall': 1.0,
 'test_test_gt_top1': 0.0,
 'test_test_image_gfn_frac_filter': 0.0,
 'test_test_image_gfn_mAP': 0.006135242146047593,
 'test_test_image_gfn_thresh_filter': nan,
 'test_test_image_gfn_top1': 0.0}
```
[gfn-30e.log](https://github.com/LukeJaffe/GFN/files/9943293/gfn-30e.log)

**Comment by LukeJaffe** [comment]
The detector performance looks good (test_ap@0.5, test_recall@0.5), but yes re-id performance is erroneous. Even an untrained model should score higher than zero for ground truth re-id (test_test_gt_top1, test_test_gt_mAP). Could you upload the config used for training? And if you run with debug=False, and upload the tensorboard log files, that will make it easier to see if the losses are decreasing properly.

**Comment by dustasa** [comment]
I have tried set debug=False and set batch size to 6(RL exps are running which take 3GB memory) and got the newest result as follow, it seems all right now. Thanks for your excellent work.
```python
(func pid=2490495) 2022-11-09 07:29:50,931	INFO trainable.py:93 -- Checkpoint size is 1784943994 bytes
Result for WrappedDistributedTorchTrainable_b1a15_00000:
  date: 2022-11-09_07-29-00
  done: true
  epoch: 29
  experiment_id: 3f21a9f071394baea2201a2b1379e651
  experiment_tag: '0'
  gfn_loss: 0.5375721454620361
  hostname: nv90ti-System-Product-Name
  iterations_since_restore: 30
  loss: 1.755976676940918
  loss_box_cls: 0.0445421002805233
  loss_box_reg: 0.10264333337545395
  loss_proposal_cls: 0.05583915114402771
  loss_proposal_reg: 0.8338098526000977
  loss_rpn_cls: 0.0033914248924702406
  loss_rpn_reg: 0.003969104029238224
  lr: 9.999999974752427e-07
  node_ip: 10.51.17.240
  pid: 2490427
  should_checkpoint: true
  sim_loss: 0.17420968413352966
  test_ap@0.5: 0.9350039765297451
  test_recall@0.5: 0.9566674646875748
  test_test_det_gfn_mAP: 0.5807063736448932
  test_test_det_gfn_match: 1.0
  test_test_det_gfn_recall: 0.9783459972511086
  test_test_det_gfn_top1: 0.9227029654837141
  test_test_det_mAP: 0.5704228825236451
  test_test_det_match: 1.0
  test_test_det_recall: 0.9783459972511086
  test_test_det_top1: 0.8857559552746719
  test_test_gt_gfn_mAP: 0.5979332395033004
  test_test_gt_gfn_match: 1.0
  test_test_gt_gfn_recall: 1.0
  test_test_gt_gfn_top1: 0.93048128342246
  test_test_gt_mAP: 0.586802793622416
  test_test_gt_match: 1.0
  test_test_gt_recall: 1.0
  test_test_gt_top1: 0.8935342732134176
  test_test_image_gfn_frac_filter: 0.1358287164902841
  test_test_image_gfn_mAP: 0.21606140440797808
  test_test_image_gfn_thresh_filter: 0.49067866802215576
  test_test_image_gfn_top1: 0.7933884297520661
  time_since_restore: 41412.86073565483
  time_this_iter_s: 5369.77135181427
  time_total_s: 41412.86073565483
  timestamp: 1667950140
  timesteps_since_restore: 0
  training_iteration: 30
  trial_id: b1a15_00000
  warmup_time: 1.8786044120788574
```

**Comment by LukeJaffe** [comment]
Thanks for this update! Glad you got it running. It's possible the training is less stable with lower batch sizes, explaining your original result with batch_size=4.
