### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by shijie2458** [LukeJaffe/GFN#8]
(bcsj) [G19830015@admin1 GFN-main]$ osr_run --trial_config=./configs/cuhk_train_final.yaml
Traceback (most recent call last):
  File "/public/home/G19830015/.local/bin/osr_run", line 33, in <module>
    sys.exit(load_entry_point('osr-lib==1.1.0', 'console_scripts', 'osr_run')())
  File "/public/home/G19830015/.local/bin/osr_run", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/public/home/G19830015/miniconda3/envs/bcsj/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 209, in load
    module = import_module(match.group('module'))
  File "/public/home/G19830015/miniconda3/envs/bcsj/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/public/home/G19830015/.local/lib/python3.7/site-packages/osr_lib-1.1.0-py3.7.egg/osr/engine/main.py", line 21, in <module>
ModuleNotFoundError: No module named 'ray.tune.integration.torch'

**Comment by LukeJaffe** [comment]
This looks like an API change in the ray tune library. Try downgrading ray tune to version 1.13.0 (known good from Dockerfile).

**Comment by shijie2458** [comment]
> 
I'm glad to receive your reply, but there are new issues that have arisen，I'm trying to find a way [https://github.com/ray-project/ray/issues/16926]but,the same error prompt still appears.

Traceback (most recent call last):
  File "/public/home/G19830015/.local/bin/osr_run", line 33, in <module>
    sys.exit(load_entry_point('osr-lib==1.1.0', 'console_scripts', 'osr_run')())
  File "/public/home/G19830015/.local/lib/python3.7/site-packages/osr_lib-1.1.0-py3.7.egg/osr/engine/main.py", line 247, in main
  File "/public/home/G19830015/miniconda3/envs/bcsj/lib/python3.7/site-packages/ray/tune/tune.py", line 741, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [WrappedDistributedTorchTrainable_4210d_00000])

**Comment by LukeJaffe** [comment]
Is that the full error, or can you post the full error if not?

**Comment by shijie2458** [comment]
> Is that the full error, or can you post the full error if not?

okey，
[error.txt](https://github.com/LukeJaffe/GFN/files/11175676/error.txt)

**Comment by LukeJaffe** [comment]
This error is occurring when torchvision tries to download pretrained weights for the convnext model. It is a URL error:
(func pid=342357)     raise URLError(err)
(func pid=342357) urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

Looks like an internet access or firewall issue.
